# Generated by Django 5.2.9 on 2025-12-17 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_secure', '0002_doctorpatientrequest'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileActionRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('upload', 'Upload'), ('edit', 'Edit'), ('delete', 'Delete')], max_length=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('file_data', models.FileField(blank=True, help_text='File data for upload/edit actions', null=True, upload_to='pending_files/')),
                ('file_name', models.CharField(blank=True, help_text='Name for the file', max_length=255)),
                ('file_description', models.TextField(blank=True, help_text='Description for the file')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_action_requests', to='med_secure.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_action_requests', to='med_secure.patient')),
                ('target_file', models.ForeignKey(blank=True, help_text='The file being edited or deleted', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pending_actions', to='med_secure.medicalfile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
