# Generated by Django 5.2.9 on 2025-12-17 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_secure', '0003_fileactionrequest'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='doctorpatientrequest',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='doctorpatientrequest',
            name='action_type',
            field=models.CharField(choices=[('add', 'Add'), ('remove', 'Remove')], default='add', help_text='Type of action: add or remove relationship', max_length=10),
        ),
    ]
