# Generated by Django 5.2.8 on 2025-12-23 00:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_secure', '0005_alter_doctorpatientrequest_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SharedEncryptionKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('encrypted_key', models.TextField(help_text="Patient's encryption key encrypted with doctor's key")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_keys', to='med_secure.doctor')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shared_keys', to='med_secure.patient')),
            ],
            options={
                'indexes': [models.Index(fields=['patient', 'doctor'], name='med_secure__patient_c983cf_idx')],
                'unique_together': {('patient', 'doctor')},
            },
        ),
    ]
