# Generated by Django 5.2.8 on 2026-01-04 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_secure', '0006_sharedencryptionkey'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='encrypted_first_name',
            field=models.TextField(blank=True, help_text='Client-side encrypted first name (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='encrypted_last_name',
            field=models.TextField(blank=True, help_text='Client-side encrypted last name (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='encrypted_organisation',
            field=models.TextField(blank=True, help_text='Client-side encrypted organisation (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientrequest',
            name='encrypted_date',
            field=models.TextField(blank=True, help_text='Client-side encrypted examination date (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientrequest',
            name='encrypted_description',
            field=models.TextField(blank=True, help_text='Client-side encrypted description (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientrequest',
            name='encrypted_name',
            field=models.TextField(blank=True, help_text='Client-side encrypted file name (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='fileactionrequest',
            name='encrypted_file_date',
            field=models.TextField(blank=True, help_text='Client-side encrypted examination date (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='fileactionrequest',
            name='encrypted_file_description',
            field=models.TextField(blank=True, help_text='Client-side encrypted description (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='fileactionrequest',
            name='encrypted_file_name',
            field=models.TextField(blank=True, help_text='Client-side encrypted file name (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='encrypted_date_of_birth',
            field=models.TextField(blank=True, help_text='Client-side encrypted date of birth (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='encrypted_first_name',
            field=models.TextField(blank=True, help_text='Client-side encrypted first name (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='encrypted_last_name',
            field=models.TextField(blank=True, help_text='Client-side encrypted last name (AES-256)', null=True),
        ),
    ]
