# Generated by Django 5.2.8 on 2026-01-04 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_secure', '0007_add_encrypted_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicalfile',
            name='encrypted_date',
            field=models.TextField(blank=True, help_text='Client-side encrypted examination date (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='encrypted_description',
            field=models.TextField(blank=True, help_text='Client-side encrypted description (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='medicalfile',
            name='encrypted_name',
            field=models.TextField(blank=True, help_text='Client-side encrypted file name (AES-256)', null=True),
        ),
    ]
