# Generated by Django 5.2.8 on 2026-01-04 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_secure', '0008_medicalfile_encrypted_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='medicalfile',
            name='description',
            field=models.TextField(blank=True, default='', help_text='Anonymized placeholder - real data in encrypted_description'),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='name',
            field=models.CharField(default='[ENCRYPTED]', help_text='Anonymized placeholder - real data in encrypted_name', max_length=255),
        ),
    ]
