# Generated by Django 5.2.8 on 2026-01-05 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_secure', '0009_anonymize_plaintext_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='doctor',
            name='encrypted_first_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='encrypted_last_name',
        ),
        migrations.RemoveField(
            model_name='doctor',
            name='encrypted_organisation',
        ),
        migrations.RemoveField(
            model_name='doctorpatientrequest',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='doctorpatientrequest',
            name='encrypted_date',
        ),
        migrations.RemoveField(
            model_name='doctorpatientrequest',
            name='encrypted_description',
        ),
        migrations.RemoveField(
            model_name='doctorpatientrequest',
            name='encrypted_name',
        ),
        migrations.RemoveField(
            model_name='doctorpatientrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='fileactionrequest',
            name='action_type',
        ),
        migrations.RemoveField(
            model_name='fileactionrequest',
            name='file_description',
        ),
        migrations.RemoveField(
            model_name='fileactionrequest',
            name='file_name',
        ),
        migrations.RemoveField(
            model_name='fileactionrequest',
            name='status',
        ),
        migrations.RemoveField(
            model_name='medicalfile',
            name='description',
        ),
        migrations.RemoveField(
            model_name='medicalfile',
            name='name',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='date_of_birth',
        ),
        migrations.AddField(
            model_name='doctorpatientrequest',
            name='encrypted_action_type',
            field=models.TextField(blank=True, help_text='Client-side encrypted action type: add or remove relationship (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='doctorpatientrequest',
            name='encrypted_status',
            field=models.TextField(blank=True, help_text='Client-side encrypted status: pending, approved, or rejected (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='fileactionrequest',
            name='encrypted_action_type',
            field=models.TextField(blank=True, help_text='Client-side encrypted action type: upload, edit, or delete (AES-256)', null=True),
        ),
        migrations.AddField(
            model_name='fileactionrequest',
            name='encrypted_status',
            field=models.TextField(blank=True, help_text='Client-side encrypted status: pending, approved, or rejected (AES-256)', null=True),
        ),
    ]
