# Generated by Django 5.2.8 on 2026-01-05 18:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('med_secure', '0010_remove_doctor_encrypted_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='doctorpatientrequest',
            old_name='encrypted_action_type',
            new_name='action_type',
        ),
        migrations.RenameField(
            model_name='doctorpatientrequest',
            old_name='encrypted_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='fileactionrequest',
            old_name='encrypted_action_type',
            new_name='action_type',
        ),
        migrations.RenameField(
            model_name='fileactionrequest',
            old_name='encrypted_file_date',
            new_name='file_date',
        ),
        migrations.RenameField(
            model_name='fileactionrequest',
            old_name='encrypted_file_description',
            new_name='file_description',
        ),
        migrations.RenameField(
            model_name='fileactionrequest',
            old_name='encrypted_file_name',
            new_name='file_name',
        ),
        migrations.RenameField(
            model_name='fileactionrequest',
            old_name='encrypted_status',
            new_name='status',
        ),
        migrations.RenameField(
            model_name='medicalfile',
            old_name='encrypted_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='medicalfile',
            old_name='encrypted_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='medicalfile',
            old_name='encrypted_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='encrypted_date_of_birth',
            new_name='date_of_birth',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='encrypted_first_name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='patient',
            old_name='encrypted_last_name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='sharedencryptionkey',
            old_name='encrypted_key',
            new_name='key',
        ),
    ]
