# Generated by Django 5.2.8 on 2026-01-05 18:40

import med_secure.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('med_secure', '0011_rename_encrypted_action_type_doctorpatientrequest_action_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fileactionrequest',
            name='file_data',
            field=models.FileField(blank=True, help_text='File data for upload/edit actions', null=True, upload_to=med_secure.models.pending_file_path),
        ),
        migrations.AlterField(
            model_name='medicalfile',
            name='file',
            field=models.FileField(upload_to=med_secure.models.encrypted_file_path),
        ),
    ]
